/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package campeonato;

/**
 *
 * @author a1420127
 */
public class Competição extends javax.swing.JPanel {

    /**
     * Creates new form Competição
     */
    public Competição() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_TelaCompetição = new javax.swing.JPanel();
        jL_NomeJogo = new javax.swing.JLabel();
        jL_jogo4 = new javax.swing.JLabel();
        jL_jogo1 = new javax.swing.JLabel();
        jL_jogo3 = new javax.swing.JLabel();
        jL_jogo2 = new javax.swing.JLabel();
        jL_jogo6 = new javax.swing.JLabel();
        jL_jogo7 = new javax.swing.JLabel();
        jL_jogo5 = new javax.swing.JLabel();
        jL_jogo8 = new javax.swing.JLabel();
        rbAdv2_1 = new javax.swing.JRadioButton();
        rbAdv1_1 = new javax.swing.JRadioButton();
        btSortear = new javax.swing.JButton();
        btLimparRes = new javax.swing.JButton();
        btProxRodada = new javax.swing.JButton();
        rbAdv3_2 = new javax.swing.JRadioButton();
        rbAdv6_3v = new javax.swing.JRadioButton();
        rbAdv5_3v = new javax.swing.JRadioButton();
        rbAdv12_6v = new javax.swing.JRadioButton();
        rbAdv11_6v = new javax.swing.JRadioButton();
        rbAdv13_7v = new javax.swing.JRadioButton();
        rbAdv14_7v = new javax.swing.JRadioButton();
        rbAdv15_8 = new javax.swing.JRadioButton();
        rbAdv16_8 = new javax.swing.JRadioButton();
        rbAdv9_5v = new javax.swing.JRadioButton();
        rbAdv10_5v = new javax.swing.JRadioButton();
        rbAdvQ4_1 = new javax.swing.JRadioButton();
        rbAdvQ4_2 = new javax.swing.JRadioButton();
        jL_Q4 = new javax.swing.JLabel();
        jL_Q3 = new javax.swing.JLabel();
        rbAdvQ3_1 = new javax.swing.JRadioButton();
        rbAdvQ3_2 = new javax.swing.JRadioButton();
        rbAdv7_4 = new javax.swing.JRadioButton();
        rbAdv8_4 = new javax.swing.JRadioButton();
        rbAdv4_2 = new javax.swing.JRadioButton();
        rbAdvQ2_1 = new javax.swing.JRadioButton();
        rbAdvQ2_2 = new javax.swing.JRadioButton();
        jL_Q2 = new javax.swing.JLabel();
        rbAdvQ1_2 = new javax.swing.JRadioButton();
        rbAdvQ1_1 = new javax.swing.JRadioButton();
        jL_Q1 = new javax.swing.JLabel();
        rbAdvS1_1 = new javax.swing.JRadioButton();
        rbAdvS1_2 = new javax.swing.JRadioButton();
        jL_S1 = new javax.swing.JLabel();
        rbAdvF_1 = new javax.swing.JRadioButton();
        rbAdvF_2 = new javax.swing.JRadioButton();
        jL_Campeão = new javax.swing.JLabel();
        rbAdvS2_1 = new javax.swing.JRadioButton();
        rbAdvS2_2 = new javax.swing.JRadioButton();
        jL_S2 = new javax.swing.JLabel();
        rbAdvCamp = new javax.swing.JRadioButton();
        jL_Final = new javax.swing.JLabel();

        jP_TelaCompetição.setBackground(new java.awt.Color(153, 255, 153));

        jL_NomeJogo.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        jL_NomeJogo.setForeground(new java.awt.Color(204, 0, 0));
        jL_NomeJogo.setText("Play Tênis");
        jL_NomeJogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jL_jogo4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jL_jogo4.setText("Jogo 4");

        jL_jogo1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jL_jogo1.setText("Jogo 1");

        jL_jogo3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jL_jogo3.setText("Jogo 3");

        jL_jogo2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jL_jogo2.setText("Jogo 2");

        jL_jogo6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jL_jogo6.setText("Jogo 6");

        jL_jogo7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jL_jogo7.setText("Jogo 7");

        jL_jogo5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jL_jogo5.setText("Jogo 5");

        jL_jogo8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jL_jogo8.setText("Jogo 8");

        btSortear.setText("Sortear Jogos");
        btSortear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSortearActionPerformed(evt);
            }
        });

        btLimparRes.setText("Limpar Resultados");
        btLimparRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparResActionPerformed(evt);
            }
        });

        btProxRodada.setText("Próxima Rodada");
        btProxRodada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProxRodadaActionPerformed(evt);
            }
        });

        rbAdv13_7v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAdv13_7vActionPerformed(evt);
            }
        });

        rbAdv14_7v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAdv14_7vActionPerformed(evt);
            }
        });

        jL_Q4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jL_Q4.setText("Quartas de Final 4");

        jL_Q3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jL_Q3.setText("Quartas de Final 3");

        jL_Q2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jL_Q2.setText("Quartas de Final 2");

        jL_Q1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jL_Q1.setText("Quartas de Final 1");

        jL_S1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jL_S1.setText("Semifinal 1");

        jL_Campeão.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jL_Campeão.setText("Campeão");

        jL_S2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jL_S2.setText("Semifinal 2");

        jL_Final.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jL_Final.setText("Final");

        javax.swing.GroupLayout jP_TelaCompetiçãoLayout = new javax.swing.GroupLayout(jP_TelaCompetição);
        jP_TelaCompetição.setLayout(jP_TelaCompetiçãoLayout);
        jP_TelaCompetiçãoLayout.setHorizontalGroup(
            jP_TelaCompetiçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_TelaCompetiçãoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_TelaCompetiçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_TelaCompetiçãoLayout.createSequentialGroup()
                        .addComponent(rbAdv1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rbAdv2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(664, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_TelaCompetiçãoLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jL_jogo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jL_jogo2)
                        .addGap(165, 165, 165)
                        .addComponent(jL_jogo3)
                        .addGap(166, 166, 166)
                        .addComponent(jL_jogo4)
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_TelaCompetiçãoLayout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(rbAdv3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rbAdv4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbAdv5_3v, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rbAdv6_3v, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(rbAdv7_4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rbAdv8_4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jP_TelaCompetiçãoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_TelaCompetiçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_TelaCompetiçãoLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jL_jogo5)
                        .addGap(170, 170, 170)
                        .addComponent(jL_jogo6)
                        .addGap(157, 157, 157)
                        .addComponent(jL_jogo7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jL_jogo8)
                        .addGap(80, 80, 80))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_TelaCompetiçãoLayout.createSequentialGroup()
                        .addComponent(rbAdv9_5v, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rbAdv10_5v, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(rbAdv11_6v, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rbAdv12_6v, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jP_TelaCompetiçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jP_TelaCompetiçãoLayout.createSequentialGroup()
                                .addComponent(rbAdv13_7v, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(rbAdv14_7v, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(rbAdv15_8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(rbAdv16_8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jP_TelaCompetiçãoLayout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(rbAdvS2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(rbAdvS2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jL_Q3))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_TelaCompetiçãoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jL_NomeJogo)
                .addGap(297, 297, 297))
            .addGroup(jP_TelaCompetiçãoLayout.createSequentialGroup()
                .addGroup(jP_TelaCompetiçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_TelaCompetiçãoLayout.createSequentialGroup()
                        .addGap(387, 387, 387)
                        .addComponent(jL_Campeão))
                    .addGroup(jP_TelaCompetiçãoLayout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(rbAdvF_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(rbAdvF_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jP_TelaCompetiçãoLayout.createSequentialGroup()
                        .addGap(400, 400, 400)
                        .addComponent(jL_Final)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_TelaCompetiçãoLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(btSortear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jP_TelaCompetiçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbAdvCamp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jP_TelaCompetiçãoLayout.createSequentialGroup()
                        .addComponent(btLimparRes)
                        .addGap(130, 130, 130)
                        .addComponent(btProxRodada)))
                .addGap(109, 109, 109))
            .addGroup(jP_TelaCompetiçãoLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jP_TelaCompetiçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_TelaCompetiçãoLayout.createSequentialGroup()
                        .addComponent(rbAdvS1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(rbAdvS1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(529, Short.MAX_VALUE))
                    .addGroup(jP_TelaCompetiçãoLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jL_S1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jL_S2)
                        .addGap(149, 149, 149))))
            .addGroup(jP_TelaCompetiçãoLayout.createSequentialGroup()
                .addGroup(jP_TelaCompetiçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jP_TelaCompetiçãoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jP_TelaCompetiçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jP_TelaCompetiçãoLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jL_Q1)
                                .addGap(47, 47, 47)
                                .addComponent(rbAdvQ2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rbAdvQ2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(271, 271, 271)
                                .addComponent(rbAdvQ4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbAdvQ4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jP_TelaCompetiçãoLayout.createSequentialGroup()
                                .addComponent(rbAdvQ1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rbAdvQ1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(252, 252, 252)
                                .addComponent(rbAdvQ3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbAdvQ3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(214, 214, 214))))
                    .addGroup(jP_TelaCompetiçãoLayout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jL_Q2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jL_Q4)
                        .addGap(18, 18, 18)))
                .addContainerGap())
        );
        jP_TelaCompetiçãoLayout.setVerticalGroup(
            jP_TelaCompetiçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_TelaCompetiçãoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_NomeJogo)
                .addGap(18, 18, 18)
                .addGroup(jP_TelaCompetiçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_TelaCompetiçãoLayout.createSequentialGroup()
                        .addGroup(jP_TelaCompetiçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jL_jogo4)
                            .addComponent(jL_jogo3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jP_TelaCompetiçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbAdv3_2)
                            .addComponent(rbAdv6_3v)
                            .addComponent(rbAdv7_4)
                            .addComponent(rbAdv8_4)
                            .addComponent(rbAdv5_3v)))
                    .addGroup(jP_TelaCompetiçãoLayout.createSequentialGroup()
                        .addGroup(jP_TelaCompetiçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jL_jogo1)
                            .addComponent(jL_jogo2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jP_TelaCompetiçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbAdv2_1)
                            .addComponent(rbAdv1_1)
                            .addComponent(rbAdv4_2))))
                .addGap(32, 32, 32)
                .addGroup(jP_TelaCompetiçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_TelaCompetiçãoLayout.createSequentialGroup()
                        .addGroup(jP_TelaCompetiçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jL_jogo6)
                            .addComponent(jL_jogo7)
                            .addComponent(jL_jogo8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jP_TelaCompetiçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jP_TelaCompetiçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rbAdv10_5v, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(rbAdv9_5v, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_TelaCompetiçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbAdv12_6v)
                                    .addComponent(rbAdv11_6v)))
                            .addGroup(jP_TelaCompetiçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_TelaCompetiçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbAdv16_8)
                                    .addComponent(rbAdv15_8))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_TelaCompetiçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbAdv14_7v)
                                    .addComponent(rbAdv13_7v)))))
                    .addComponent(jL_jogo5))
                .addGap(66, 66, 66)
                .addGroup(jP_TelaCompetiçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jP_TelaCompetiçãoLayout.createSequentialGroup()
                        .addGroup(jP_TelaCompetiçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jL_Q3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jL_Q2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jP_TelaCompetiçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jL_Q4)))
                        .addGroup(jP_TelaCompetiçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jP_TelaCompetiçãoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jP_TelaCompetiçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbAdvQ2_1)
                                    .addComponent(rbAdvQ2_2)
                                    .addComponent(rbAdvQ3_2)
                                    .addComponent(rbAdvQ3_1)
                                    .addComponent(rbAdvQ4_2)
                                    .addComponent(rbAdvQ4_1)))
                            .addGroup(jP_TelaCompetiçãoLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(rbAdvQ1_2))))
                    .addGroup(jP_TelaCompetiçãoLayout.createSequentialGroup()
                        .addComponent(jL_Q1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbAdvQ1_1)))
                .addGap(46, 46, 46)
                .addGroup(jP_TelaCompetiçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_S1)
                    .addComponent(jL_S2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jP_TelaCompetiçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_TelaCompetiçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(rbAdvS2_1)
                        .addGroup(jP_TelaCompetiçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbAdvS1_1)
                            .addComponent(rbAdvS1_2)))
                    .addComponent(rbAdvS2_2))
                .addGap(41, 41, 41)
                .addComponent(jL_Final)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_TelaCompetiçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbAdvF_1)
                    .addComponent(rbAdvF_2))
                .addGap(24, 24, 24)
                .addComponent(jL_Campeão)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbAdvCamp)
                .addGap(61, 61, 61)
                .addGroup(jP_TelaCompetiçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSortear, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLimparRes, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btProxRodada, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_TelaCompetição, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_TelaCompetição, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rbAdv14_7vActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAdv14_7vActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbAdv14_7vActionPerformed

    private void btProxRodadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProxRodadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btProxRodadaActionPerformed

    private void btLimparResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparResActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btLimparResActionPerformed

    private void btSortearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSortearActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_btSortearActionPerformed

    private void rbAdv13_7vActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAdv13_7vActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbAdv13_7vActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLimparRes;
    private javax.swing.JButton btProxRodada;
    private javax.swing.JButton btSortear;
    private javax.swing.JLabel jL_Campeão;
    private javax.swing.JLabel jL_Final;
    private javax.swing.JLabel jL_NomeJogo;
    private javax.swing.JLabel jL_Q1;
    private javax.swing.JLabel jL_Q2;
    private javax.swing.JLabel jL_Q3;
    private javax.swing.JLabel jL_Q4;
    private javax.swing.JLabel jL_S1;
    private javax.swing.JLabel jL_S2;
    private javax.swing.JLabel jL_jogo1;
    private javax.swing.JLabel jL_jogo2;
    private javax.swing.JLabel jL_jogo3;
    private javax.swing.JLabel jL_jogo4;
    private javax.swing.JLabel jL_jogo5;
    private javax.swing.JLabel jL_jogo6;
    private javax.swing.JLabel jL_jogo7;
    private javax.swing.JLabel jL_jogo8;
    private javax.swing.JPanel jP_TelaCompetição;
    private javax.swing.JRadioButton rbAdv10_5v;
    private javax.swing.JRadioButton rbAdv11_6v;
    private javax.swing.JRadioButton rbAdv12_6v;
    private javax.swing.JRadioButton rbAdv13_7v;
    private javax.swing.JRadioButton rbAdv14_7v;
    private javax.swing.JRadioButton rbAdv15_8;
    private javax.swing.JRadioButton rbAdv16_8;
    private javax.swing.JRadioButton rbAdv1_1;
    private javax.swing.JRadioButton rbAdv2_1;
    private javax.swing.JRadioButton rbAdv3_2;
    private javax.swing.JRadioButton rbAdv4_2;
    private javax.swing.JRadioButton rbAdv5_3v;
    private javax.swing.JRadioButton rbAdv6_3v;
    private javax.swing.JRadioButton rbAdv7_4;
    private javax.swing.JRadioButton rbAdv8_4;
    private javax.swing.JRadioButton rbAdv9_5v;
    private javax.swing.JRadioButton rbAdvCamp;
    private javax.swing.JRadioButton rbAdvF_1;
    private javax.swing.JRadioButton rbAdvF_2;
    private javax.swing.JRadioButton rbAdvQ1_1;
    private javax.swing.JRadioButton rbAdvQ1_2;
    private javax.swing.JRadioButton rbAdvQ2_1;
    private javax.swing.JRadioButton rbAdvQ2_2;
    private javax.swing.JRadioButton rbAdvQ3_1;
    private javax.swing.JRadioButton rbAdvQ3_2;
    private javax.swing.JRadioButton rbAdvQ4_1;
    private javax.swing.JRadioButton rbAdvQ4_2;
    private javax.swing.JRadioButton rbAdvS1_1;
    private javax.swing.JRadioButton rbAdvS1_2;
    private javax.swing.JRadioButton rbAdvS2_1;
    private javax.swing.JRadioButton rbAdvS2_2;
    // End of variables declaration//GEN-END:variables
}
